name: Build and Deploy Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz cmake ninja-build

      - name: Configure
        run: cmake -B build -G Ninja -DBUILD_DOXYGEN=ON

      - name: Build docs
        run: |
          cmake --build build --target mylib_doc

      - name: Deploy docs to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          ssh_private_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: build/docs
